version: "3.9"

services:
  db:
    image: mongo
    container_name: mongo-container
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "27019:27017"
    volumes:
      - ./db-data:/data/db
    networks:
      - app_network

  server:
    build: ./backend
    image: app-server
    container_name: server-container
    environment:
      PORT: ${SERVER_PORT}
      DB_URI: "mongodb://${DB_USERNAME}:${DB_PASSWORD}@db/${DB_DATABASE}"
    expose:
      - ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./backend:/app
    networks:
      - app_network

  client:
    build: ./frontend
    image: app-client
    container_name: client-container
    environment:
      PORT: ${CLIENT_PORT}
    expose:
      - ${CLIENT_PORT}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./frontend:/app
    networks:
      - app_network

#volumes:
#  db_data:

networks:
  app_network:
    driver: bridge
