version: "3.9"

services:
  db:
    image: mongo
    container_name: mongo-container
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "27019:27017"
#    volumes:
#      - "db-data:/data/db"
#    networks:
#      - app_network

#volumes:
#  db_data:
#
#networks:
#  app_network:
#    driver: bridge